#!/usr/bin/env bash
# script to display domain information

checkdomain() {
    if [ -z "$1" ]; then
        echo "Usage: $0 <domain> [subdomain]"
        exit 1
    fi

    domain="$1"
    subdomain="$2"

    if [ -z "$subdomain" ]; then
        subdomains='www lb-01 web-01 web-02'
    else
        subdomains="$subdomain"
    fi

    for sub in $subdomains; do
        result=$(dig "$sub.$domain" +short)

        if [ -z "$result" ]; then
            echo "No information found for $sub.$domain"
        else
            record_type=$(dig "$sub.$domain" | awk '/^;; ANSWER SECTION:/{getline; print $4}')
            destination=$(dig "$sub.$domain" +short)
            echo "The subdomain $sub is a $record_type record and points to $destination"
        fi
    done
}

checkdomain "$1" "$2"
