#!/usr/bin/env bash
# Bash script to install and configure Nginx on an Ubuntu machine.
# The default webpage is set to "Hello World!"
# It also configures redirection to a YouTube channel and serves a custom 404 page.

# Update the package list
sudo apt-get update -y

# Install Nginx
sudo apt-get install nginx -y

# Create a simple default webpage
echo "Hello World!" | sudo dd status=none of=/var/www/html/index.html

# Create a custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null

# Configure redirection to a YouTube channel
REDIRECT_RULE="\\\n\tlocation /redirect_me {\n\t\t return 301 https://www.youtube.com/@innocentsax;\n\t}\n"
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.backup
sudo sed -i "53i $REDIRECT_RULE" /etc/nginx/sites-available/default

# Configure custom 404 page
ERROR_PAGE_RULE="\\\n\terror_page 404 /404.html;\n\n\tlocation = /404.html {\n\t\tinternal;\n\t}\n"
sudo sed -i "53i $ERROR_PAGE_RULE" /etc/nginx/sites-available/default

# Reload Nginx to apply the changes
sudo service nginx reload

echo "Nginx installation and configuration completed. ✔"
