#!/usr/bin/env bash
# Bash script to configure Nginx with a custom 404 page.

# Update the package list
sudo apt-get update -y

# Install Nginx
sudo apt-get install nginx -y

# Create a custom 404 page
echo -e '<html><head><title>404 Not Found</title></head><body><h1>Ceci n'\''est pas une page</h1></body></html>' | sudo tee /var/www/html/404.html > /dev/null

# Configure Nginx to use the custom 404 page
CONFIG_RULE="\
\n\terror_page 404 /404.html;\n\n\
\tlocation = /404.html {\n\t\tinternal;\n\t}\n"
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.backup
sudo sed -i "/error_page 404/d" /etc/nginx/sites-available/default
sudo sed -i "/location = \/404.html {/d" /etc/nginx/sites-available/default
sudo sed -i "53i $CONFIG_RULE" /etc/nginx/sites-available/default

# Reload Nginx to apply the changes
sudo service nginx reload

echo "Nginx configuration for custom 404 page completed. ✔"
