#!/usr/bin/env bash
# Install Ningx if not already installed
sudo apt-get update
sudo apt-get install -y nginx

# Nginx configuration file path
nginx_conf="/etc/nginx/sites-available/default"

# Add the custom header configuration
sudo tee -a "$nginx_conf" > /dev/null <<EOL

# Custom header configuration
server {
    # ... other server configurations ...

    # Add the custom header
    add_header X-Served-By \$hostname;

}
EOL

# Restart Nginx to apply changes
sudo systemctl restart nginx
