#!/bin/env bash
# Install Ningx if not already installed
sudo apt-get update
sudo apt-get install -y nginx

# Define the custom header value

HEADER_VALUE=$(hostname)

# Configure Nginx to include the custom header
CONFIG_FILE="/etc/nginx/sites-available/default"

# Reload the customer configuration to the server block
sudo sed -i '/server {/a \\tadd_header X-Served-By "$HEADER_VALUE";' $CONFIG_FILE

# Reload Nginx to apply the changes
sudo service nginx restart
