#!/usr/bin/env bash
# Exit on errors
set -e

# Update package list and install HAProxy
sudo apt-get update -y
sudo apt-get install -y haproxy

# Configure HAProxy
sudo mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak  # Backup the default configuration file

# Create a new HAProxy configuration file
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOL
global
    log /dev/log local0
    log /dev/log local1 notice
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    retries 3
    option redispatch
    timeout connect 5s
    timeout client 15s
    timeout server 15s

frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 100.26.9.108:80 check
    server web-02 34.207.57.168:80 check
EOL

# Restart HAProxy to apply changes
sudo systemctl restart haproxy

echo "HAProxy configuration completed successfully."
