#!/usr/bin/env bash
# This script installs and configures HAproxy on lb-01 server

# Update package list and install HAproxy
sudo apt-get -y update
sudo apt-get -y install haproxy

# Configure HAproxy
sudo bash -c 'cat > /etc/haproxy/haproxy.cfg <<EOF
frontend web_frontend
    bind 0:80
    timeout client 30s
    default_backend web_servers

backend web_servers
    balance roundrobin
    timeout server 30s
    server web-01 100.26.9.108
    server web-02 34.207.57.168
EOF'

# Restart HAproxy service
sudo service haproxy restart

# Ensure HAproxy is managed via an init script
sudo systemctl enable haproxy

# Verify HAproxy configuration
sudo haproxy -c -V -f /etc/haproxy/haproxy.cfg
