#!/usr/bin/env bash
# Display the content of the file /etc/passwd
# Display username, user id, and home directory path for each user

while IFS=":" read -r username x userid x homepath x; do
  echo "$username:$userid:$homepath"
done < "/etc/passwd"
