#!/usr/bin/env bash

#set the file path

file="/etc/passwd"


IF=":"


while read -r username x userid x homepath x; do

       
       echo "Username: $username"
       echo "User ID: $userid"
       echo "Home Directory: $homepath"
done < "$file"
