#!/usr/bin/env bash
# Display the content of the file /etc/passwd with a story

while IFS=":" read -r username x userid homepath shell; do
  echo "The user $username is part of the $userid gang, lives in $homepath and rides $shell. $userid's place is protected by the passcode x, more info about the user here: $username"
done < "/etc/passwd"
