#!/usr/bin/env bash
# Gracefully reloads Gunicorn.

# Find all Gunicorn processes
gunicorn_pids=$(pgrep gunicorn)

# If no Gunicorn processes are found, print an error message and exit with status code 1
if [ -z "$gunicorn_pids" ]; then
    echo "No Gunicorn processes found."
    exit 1
fi

# Stop old workers gracefully
echo "Stopping old workers gracefully..."
for pid in $gunicorn_pids; do
    kill -HUP "$pid"
done

# Wait for old workers to finish processing (optional)
echo "Waiting for old workers to finish processing..."
sleep 5

echo "Graceful reload complete"
